export const allColumns = [
    "Loan No",
    "Loan Type",
    "Borrower",
    "Borrower Address",
    "Co Borrower Name",
    "Co Borrower Address",
    "Current DPD",
    "Sanction Amount",
    "Region",
  ];
  
  export const tableData = [
    {
      id: 1,
      loanNo: "LN-001",
      loanType: "Home Loan",
      borrower: "John Doe",
      borrowerAddress: "123 Main St, NY",
      coBorrowerName: "Jane Doe",
      coBorrowerAddress: "456 Elm St, NY",
      currentDPD: "10",
      sanctionAmount: "$100,000",
      region: "North",
    },
    {
      id: 2,
      loanNo: "LN-002",
      loanType: "Car Loan",
      borrower: "Alice Brown",
      borrowerAddress: "789 Pine St, CA",
      coBorrowerName: "Bob Brown",
      coBorrowerAddress: "321 Oak St, CA",
      currentDPD: "5",
      sanctionAmount: "$50,000",
      region: "West",
    },
    {
      id: 3,
      loanNo: "LN-003",
      loanType: "Business Loan",
      borrower: "Charlie Smith",
      borrowerAddress: "101 Maple St, TX",
      coBorrowerName: "Daisy Smith",
      coBorrowerAddress: "202 Cedar St, TX",
      currentDPD: "15",
      sanctionAmount: "$200,000",
      region: "South",
    },
    {
      id: 4,
      loanNo: "LN-004",
      loanType: "Education Loan",
      borrower: "Emma Johnson",
      borrowerAddress: "303 Birch St, FL",
      coBorrowerName: "Frank Johnson",
      coBorrowerAddress: "404 Spruce St, FL",
      currentDPD: "0",
      sanctionAmount: "$75,000",
      region: "East",
    },
    {
      id: 5,
      loanNo: "LN-005",
      loanType: "Personal Loan",
      borrower: "George White",
      borrowerAddress: "505 Redwood St, WA",
      coBorrowerName: "Helen White",
      coBorrowerAddress: "606 Fir St, WA",
      currentDPD: "8",
      sanctionAmount: "$30,000",
      region: "Northwest",
    },
    {
      id: 6,
      loanNo: "LN-006",
      loanType: "Home Loan",
      borrower: "Daniel Green",
      borrowerAddress: "1234 Oak St, IL",
      coBorrowerName: "Sophia Green",
      coBorrowerAddress: "5678 Maple St, IL",
      currentDPD: "20",
      sanctionAmount: "$150,000",
      region: "Midwest",
    },
    {
      id: 7,
      loanNo: "LN-007",
      loanType: "Auto Loan",
      borrower: "Ryan Black",
      borrowerAddress: "999 Elm St, OH",
      coBorrowerName: "Isabella Black",
      coBorrowerAddress: "777 Pine St, OH",
      currentDPD: "3",
      sanctionAmount: "$25,000",
      region: "East",
    },
    {
      id: 8,
      loanNo: "LN-008",
      loanType: "Business Loan",
      borrower: "Oliver Gray",
      borrowerAddress: "444 Cedar St, MA",
      coBorrowerName: "Mia Gray",
      coBorrowerAddress: "222 Birch St, MA",
      currentDPD: "12",
      sanctionAmount: "$500,000",
      region: "Northeast",
    },
    {
      id: 9,
      loanNo: "LN-009",
      loanType: "Education Loan",
      borrower: "Ethan Brown",
      borrowerAddress: "789 Fir St, PA",
      coBorrowerName: "Emily Brown",
      coBorrowerAddress: "111 Redwood St, PA",
      currentDPD: "0",
      sanctionAmount: "$40,000",
      region: "Mid-Atlantic",
    },
    {
      id: 10,
      loanNo: "LN-010",
      loanType: "Personal Loan",
      borrower: "William Harris",
      borrowerAddress: "432 Main St, GA",
      coBorrowerName: "Charlotte Harris",
      coBorrowerAddress: "876 Spruce St, GA",
      currentDPD: "6",
      sanctionAmount: "$60,000",
      region: "Southeast",
    },
    {
      id: 11,
      loanNo: "LN-011",
      loanType: "Home Loan",
      borrower: "Henry Wilson",
      borrowerAddress: "567 Hill St, TX",
      coBorrowerName: "Amelia Wilson",
      coBorrowerAddress: "789 Valley St, TX",
      currentDPD: "25",
      sanctionAmount: "$250,000",
      region: "South",
    },
    {
      id: 12,
      loanNo: "LN-012",
      loanType: "Auto Loan",
      borrower: "Lucas Martinez",
      borrowerAddress: "222 Broadway, NY",
      coBorrowerName: "Harper Martinez",
      coBorrowerAddress: "555 Madison Ave, NY",
      currentDPD: "4",
      sanctionAmount: "$35,000",
      region: "North",
    },
    {
      id: 13,
      loanNo: "LN-013",
      loanType: "Business Loan",
      borrower: "Sebastian Thompson",
      borrowerAddress: "345 Ocean Dr, CA",
      coBorrowerName: "Evelyn Thompson",
      coBorrowerAddress: "678 Sunset Blvd, CA",
      currentDPD: "18",
      sanctionAmount: "$750,000",
      region: "West",
    },
    {
      id: 14,
      loanNo: "LN-014",
      loanType: "Education Loan",
      borrower: "Jack Robinson",
      borrowerAddress: "999 Highway St, NJ",
      coBorrowerName: "Sofia Robinson",
      coBorrowerAddress: "888 Parkway St, NJ",
      currentDPD: "0",
      sanctionAmount: "$55,000",
      region: "Mid-Atlantic",
    },
    {
      id: 15,
      loanNo: "LN-015",
      loanType: "Personal Loan",
      borrower: "Owen Scott",
      borrowerAddress: "555 Birch Ave, CO",
      coBorrowerName: "Lily Scott",
      coBorrowerAddress: "777 Cedar Ave, CO",
      currentDPD: "7",
      sanctionAmount: "$70,000",
      region: "Mountain West",
    }
  ];
  
  